# Generated by Django 3.2 on 2021-04-25 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_collection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
